project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from nominas import views  

app_name = "nominas"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('nominas.urls')),
]

project/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views
from nominas import views as nominas_views

app_name = 'core'

urlpatterns = [
    path('', core_views.index, name="index"),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register/', core_views.Register.as_view(), name='register'),
    path('profile/', core_views.Profile.as_view(), name='profile'),
    path('nominas/', include('nominas.urls', namespace='nominas')),
    path('about/', core_views.abou, name="about"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/nominas/urls.py
from django.contrib import admin
from django.urls import path, include
from nominas import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'nominas'

urlpatterns = [
    path("empleado/list", views.empleado_list, name="empleado_list"),
    path("novedad/list", views.novedad_list, name="novedad_list"),
    path("liquidacion/list", views.liquidacion_list, name="liquidacion_list"),
    path("empleado/form", views.empleado_form, name="empleado_form"),
    path("novedad/form", views.novedad_form, name="novedad_form"),
    path("liquidacion/form", views.liquidacion_form, name="liquidacion_form"),
    path('empleado/detail/<int:pk>', views.empleado_detail, name="empleado_detail"),
    path('liquidacion/detail/<int:pk>', views.liquidacion_detail, name="liquidacion_detail"),    
    path('empleado/update/<int:pk>', views.empleado_update, name="empleado_update"),
    path('liquidacion/update/<int:pk>', views.liquidacion_update, name="liquidacion_update"),  
    path('empleado/delete/<int:pk>', views.empleado_delete, name="empleado_delete"),
    path('liquidacion/delete/<int:pk>', views.liquidacion_delete, name="liquidacion_delete"),
    path('novedad/update/<int:pk>', views.novedad_update, name="novedad_update"),  
    path('novedad/delete/<int:pk>', views.novedad_delete, name="novedad_delete"),
    path('novedad/detail/<int:pk>', views.novedad_detail, name="novedad_detail"),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars/', blank=True, null=True)

    def __str__(self):
        return self.user.username

project/core/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

class UserProfileForm(forms.ModelForm):
    avatar = forms.ImageField(required=False)  # Añadir campo para el avatar

    class Meta:
        model = User  
        fields = ('username', 'first_name', 'last_name', 'email')  

project/core/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User  
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView  

from .forms import CustomUserCreationForm, UserProfileForm

def index(request):
    return render(request, 'core/index.html')

class Register(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'core/register.html'
    success_url = reverse_lazy('core:index')

class Profile(LoginRequiredMixin, UpdateView):
    model = User  
    form_class = UserProfileForm
    template_name = 'core/profile.html'
    success_url = reverse_lazy('core:index')

    def get_object(self):
        return self.request.user

def abou(request):
    return render(request, 'core/about.html') 

project/core/templates/core/componentes/footer.html
<p style="position: fixed; bottom: 0; left: 0; right: 0; background-color: black; color: white; text-align: center;">
    Proyecto final Python - Coderhouse 2024
</p>

project/core/templates/core/componentes/navbar.html
<nav>
    <ul style="display: flex; justify-content: center; list-style-type: none; padding: 0;">
        <li><a href="{% url 'core:index' %}"><button>Home</button></a></li>
        {% if user.is_authenticated %}
            <li><a href="{% url 'nominas:empleado_list' %}"><button>Legajos</button></a></li>
            <li><a href="{% url 'nominas:novedad_list' %}"><button>Novedades</button></a></li>
            <li><a href="{% url 'nominas:liquidacion_list' %}"><button>Liquidaciones</button></a></li>
            <li><a href="{% url 'core:about' %}"><button>About</button></a></li>
            <li><a href="{% url 'core:profile' %}"><button>{{ user.username }}</button></a></li>
            <li><a href="{% url 'core:register' %}"><button>Crear Usuario</button></a></li>
            <li>
                <form action="{% url 'core:logout' %}" method="post" style="margin: 0; display: inline;">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
        {% else %}
            <li><a href="{% url 'core:login' %}"><button>Login</button></a></li>
        {% endif %}
    </ul>
</nav>