project/config/urls.py
from django.contrib import admin
from django.urls import path, include
from nominas import views  

app_name = "nominas"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('nominas.urls')),
]

project/core/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from core import views as core_views
from nominas import views as nominas_views

app_name = 'core'

urlpatterns = [
    path('', core_views.index, name="index"),
    path('login/', LoginView.as_view(template_name='core/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='core/logout.html'), name='logout'),
    path('register/', core_views.Register.as_view(), name='register'),
    path('profile/', core_views.Profile.as_view(), name='profile'),
    path('nominas/', include('nominas.urls', namespace='nominas')),
    path('about/', core_views.abou, name="about"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/nominas/urls.py
from django.contrib import admin
from django.urls import path, include
from nominas import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'nominas'

urlpatterns = [
    path("empleado/list", views.empleado_list, name="empleado_list"),
    path("novedad/list", views.novedad_list, name="novedad_list"),
    path("liquidacion/list", views.liquidacion_list, name="liquidacion_list"),
    path("empleado/form", views.empleado_form, name="empleado_form"),
    path("novedad/form", views.novedad_form, name="novedad_form"),
    path("liquidacion/form", views.liquidacion_form, name="liquidacion_form"),
    path('empleado/detail/<int:pk>', views.empleado_detail, name="empleado_detail"),
    path('liquidacion/detail/<int:pk>', views.liquidacion_detail, name="liquidacion_detail"),    
    path('empleado/update/<int:pk>', views.empleado_update, name="empleado_update"),
    path('liquidacion/update/<int:pk>', views.liquidacion_update, name="liquidacion_update"),  
    path('empleado/delete/<int:pk>', views.empleado_delete, name="empleado_delete"),
    path('liquidacion/delete/<int:pk>', views.liquidacion_delete, name="liquidacion_delete"),
    path('novedad/update/<int:pk>', views.novedad_update, name="novedad_update"),  
    path('novedad/delete/<int:pk>', views.novedad_delete, name="novedad_delete"),
    path('novedad/detail/<int:pk>', views.novedad_detail, name="novedad_detail"),  
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/nominas/models.py
from django.db import models
from django.core.exceptions import ValidationError
from datetime import date
from decimal import Decimal
from django import forms
import calendar

class Empleado(models.Model):
    SEXO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ]
    
    ESTADO_CHOICES = [
        ('A', 'Activo'),
        ('P', 'Pasivo'),
    ]

    MOD_CONTRATACION_CHOICES = [
        ('T', 'Temporal'),
        ('P', 'Permanente'),
    ]

    nro_legajo = models.AutoField(primary_key=True)
    nombre_empleado = models.CharField(max_length=50)
    apellido_empleado = models.CharField(max_length=50)
    dni = models.CharField(max_length=8)
    sexo_empleado = models.CharField(max_length=1, choices=SEXO_CHOICES)  # Elección entre Masculino y Femenino
    celular = models.CharField(max_length=30, blank=True, null=True)
    mail = models.CharField(max_length=50, blank=True, null=True)
    fecha_de_nacimiento = models.DateField(verbose_name='Fecha de Nacimiento')
    fecha_de_ingreso = models.DateField()
    fecha_de_egreso = models.DateField(blank=True, null=True)
    estado = models.CharField(max_length=1, choices=ESTADO_CHOICES)  # Elección entre Activo y Pasivo
    nacionalidad = models.CharField(max_length=100)  # Campo para ingresar el país a mano
    mod_contratacion = models.CharField(max_length=1, choices=MOD_CONTRATACION_CHOICES, blank=True, null=True)  # Elección entre Temporal y Permanente
    puesto = models.CharField(max_length=100)
    sueldo = models.DecimalField(max_digits=10, decimal_places=2)
    avatar = models.ImageField(upload_to='avatares', blank=True, null=True)

    def clean(self):
        # Validar que la fecha de ingreso no sea posterior a la fecha de egreso
        if self.fecha_de_egreso and self.fecha_de_ingreso > self.fecha_de_egreso:
            raise ValidationError('La fecha de ingreso no puede ser posterior a la fecha de egreso.')
        
        # Validar que el empleado sea mayor de 18 años
        today = date.today()
        age = today.year - self.fecha_de_nacimiento.year - ((today.month, today.day) < (self.fecha_de_nacimiento.month, self.fecha_de_nacimiento.day))
        if age < 18:
            raise ValidationError('El empleado debe ser mayor de 18 años.')
        
        return super().clean()

    def get_fecha_de_nacimiento_display(self):
        if self.fecha_de_nacimiento:
            return self.fecha_de_nacimiento.strftime("%d/%m/%Y")
        return "Fecha no disponible"

    def __str__(self):
        return f'{self.nombre_empleado} {self.apellido_empleado} (Legajo: {self.nro_legajo}) - {self.puesto}'


class Novedad(models.Model):
    TIPO_NOVEDAD_CHOICES = [
        ('AS', 'Ausencia'),
        ('LI', 'Licencia'),
    ]
    
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    tipo_novedad = models.CharField(max_length=2, choices=TIPO_NOVEDAD_CHOICES)  # Tipo de novedad
    descripcion = models.CharField(max_length=255, blank=True, null=True)  # Descripción adicional (opcional)
    fecha = models.DateField()
    fecha_creacion = models.DateField(auto_now_add=True)  # Fecha de creación automática
    comentarios = models.TextField(blank=True, null=True)  # Comentarios adicionales (opcional)

    def __str__(self):
        return f'Novedad de {self.empleado} - {self.get_tipo_novedad_display()} ({self.fecha})'


class NovedadForm(forms.ModelForm):
    class Meta:
        model = Novedad
        fields = ['empleado', 'tipo_novedad', 'descripcion', 'fecha', 'comentarios']  # Campos a incluir

    def clean(self):
        cleaned_data = super().clean()
        empleado = cleaned_data.get('empleado')
        fecha = cleaned_data.get('fecha')

        if empleado and fecha:
            if Novedad.objects.filter(empleado=empleado, fecha=fecha).exists():
                raise forms.ValidationError("Ya existe una novedad para este legajo en la misma fecha.")


class Liquidacion(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    periodo = models.CharField(max_length=7)  # Ejemplo: "09-2024" (mes y año)
    fecha_liquidacion = models.DateField(default=date.today)
    total_dias_ausencia = models.IntegerField(default=0)
    total_liquidacion = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    fecha_pago = models.DateField()

    def calcular_total_liquidacion(self):
        # Sueldo diario (siempre basado en 30 días)
        sueldo_diario = self.empleado.sueldo / 30 if self.empleado.sueldo > 0 else 0
        print(f'Sueldo: {self.empleado.sueldo}, Sueldo Diario: {sueldo_diario}')

        # Días de ausencia cargados como "Novedad" para el empleado en el período
        ausencias = Novedad.objects.filter(
            empleado=self.empleado,
            tipo_novedad='AS',
            fecha__year=int(self.periodo.split('-')[1]),
            fecha__month=int(self.periodo.split('-')[0])
        ).count()

        # Obtener fecha de ingreso
        fecha_ingreso = self.empleado.fecha_de_ingreso

        # Inicializar días trabajados
        dias_trabajados = 30  # Siempre 30 días como base

        ultimo_dia_mes = calendar.monthrange(fecha_ingreso.year, fecha_ingreso.month)[1]
        dias_trabajados = ultimo_dia_mes - fecha_ingreso.day + 1  # Sumamos 1 para incluir el día de ingreso

        # Días trabajados después de restar ausencias
        dias_trabajados -= ausencias
        print(f'Ausencias: {ausencias}, Días Trabajados: {dias_trabajados}')

        # Calcular el sueldo bruto descontando los días no trabajados
        sueldo_bruto = dias_trabajados * sueldo_diario if sueldo_diario > 0 else 0
        print(f'Sueldo Bruto: {sueldo_bruto}')

        # Aplicar descuentos
        jubilacion = sueldo_bruto * Decimal('0.11')  # 11% de descuento para jubilación
        ley_19032 = sueldo_bruto * Decimal('0.03')  # 3% para ley 19032
        obra_social = sueldo_bruto * Decimal('0.03')  # 3% para obra social

        print(f'Jubilación: {jubilacion}, Ley 19032: {ley_19032}, Obra Social: {obra_social}')

        # Sueldo neto después de los descuentos
        sueldo_neto = sueldo_bruto - (jubilacion + ley_19032 + obra_social)
        print(f'Sueldo Neto: {sueldo_neto}')

        return sueldo_neto

    def save(self, *args, **kwargs):
        # Calculamos la liquidación antes de guardarla
        self.total_liquidacion = self.calcular_total_liquidacion()

        # Guardamos el total de ausencias en el campo correspondiente
        self.total_dias_ausencia = Novedad.objects.filter(
            empleado=self.empleado,
            tipo_novedad='AS',
            fecha__year=int(self.periodo.split('-')[1]),
            fecha__month=int(self.periodo.split('-')[0])
        ).count()

        super().save(*args, **kwargs)

    def __str__(self):
        sueldo_diario = self.empleado.sueldo / 30 if self.empleado.sueldo > 0 else 0
        sueldo_neto = self.total_liquidacion
        return (
            f'Liquidación {self.periodo} - {self.empleado.nombre_empleado} {self.empleado.apellido_empleado} '
            f'(Legajo: {self.empleado.nro_legajo}) - Días trabajados: {30 - self.total_dias_ausencia} - '
            f'Sueldo bruto: {self.empleado.sueldo:.2f} - Ausencias: {self.total_dias_ausencia} - Sueldo neto: {sueldo_neto:.2f}'
        )

project/nominas/views.py
from django.shortcuts import render, redirect
from .models import Empleado, Liquidacion, Novedad
from .forms import EmpleadoForm, NovedadForm, LiquidacionForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from decimal import Decimal
import calendar
from django.shortcuts import render, get_object_or_404

def index(request):
    return render(request, "core/index.html")

@login_required
def empleado_list(request):
    query = request.GET.get("q")
    
    if query:
         empleados = Empleado.objects.filter(
            Q(nombre_empleado__icontains=query) | Q(apellido_empleado__icontains=query)
        )
    else:
        empleados = Empleado.objects.all()
    
    context = {"object_list": empleados}
    return render(request, "nominas/empleado_list.html", context)

@login_required
def empleado_detail(request, pk: int):
    query = Empleado.objects.get(nro_legajo=pk)
    context = {'object': query}
    return render(request, 'nominas/empleado_detail.html', context)

@login_required
def novedad_list(request):
    query = request.GET.get("q")
    
    if query:
        novedades = Novedad.objects.filter(
            Q(empleado__nombre_empleado__icontains=query) | Q(empleado__apellido_empleado__icontains=query)
        )
    else:
        novedades = Novedad.objects.all()
    
    context = {"object_list": novedades}  
    return render(request, "nominas/novedad_list.html", context)

@login_required
def liquidacion_list(request):
    query = request.GET.get("q")
    
    if query:
        novedades = Liquidacion.objects.filter(
            Q(empleado__nombre_empleado__icontains=query) | Q(empleado__apellido_empleado__icontains=query)
        )
    else:
        novedades = Liquidacion.objects.all()
    
    context = {"object_list": novedades}
    return render(request, "nominas/liquidacion_list.html", context)

@login_required
def liquidacion_detail(request, pk):
    liquidacion = get_object_or_404(Liquidacion, pk=pk)

    # Lógica para calcular los datos de liquidación
    sueldo_diario = liquidacion.empleado.sueldo / 30 if liquidacion.empleado.sueldo > 0 else 0
    print(f'Sueldo: {liquidacion.empleado.sueldo}, Sueldo Diario: {sueldo_diario}')

    # Días de ausencia cargados como "Novedad" para el empleado en el período
    ausencias = Novedad.objects.filter(
        empleado=liquidacion.empleado,
        tipo_novedad='AS',
        fecha__year=int(liquidacion.periodo.split('-')[1]),
        fecha__month=int(liquidacion.periodo.split('-')[0])
    ).count()

    # Obtener fecha de ingreso
    fecha_ingreso = liquidacion.empleado.fecha_de_ingreso
    dias_trabajados = 30  # Siempre 30 días como base

    if fecha_ingreso:
        ultimo_dia_mes = calendar.monthrange(fecha_ingreso.year, fecha_ingreso.month)[1]
        dias_trabajados = ultimo_dia_mes - fecha_ingreso.day + 1  # +1 para incluir el día de ingreso

    # Días trabajados después de restar ausencias
    dias_trabajados -= ausencias  # Resta las ausencias directamente
    print(f'Ausencias: {ausencias}, Días Trabajados: {dias_trabajados}')

    # Calcular sueldo bruto y descuentos
    sueldo_bruto = dias_trabajados * sueldo_diario if sueldo_diario > 0 else 0
    jubilacion = sueldo_bruto * -Decimal('0.11')
    obra_social = sueldo_bruto * -Decimal('0.03')
    ley_19032 = sueldo_bruto * -Decimal('0.03')

    # Sueldo neto
    sueldo_neto = (sueldo_diario * dias_trabajados) - (jubilacion + obra_social + ley_19032)

    # Contexto para la plantilla
    context = {
        'object': liquidacion,
        'descuento_jubilacion': jubilacion,
        'descuento_obra_social': obra_social,
        'descuento_ley_19032': ley_19032,
        'dias_trabajados': dias_trabajados, 
        'monto_resta_ingreso': (dias_trabajados + ausencias - 30) * sueldo_diario,  # Lógica para el monto de ingreso
        'monto_resta_ausencias': ausencias * -sueldo_diario,  # Lógica para el monto de ausencias
    }

    return render(request, 'nominas/liquidacion_detail.html', context)

@login_required
def empleado_form(request):
    if request.method == "GET":
        form = EmpleadoForm()
    elif request.method == "POST":
        form = EmpleadoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("nominas:empleado_list") 
    return render(request, "nominas/empleado_form.html", {"form": form})


@login_required
def novedad_form(request):
    if request.method == "GET":
        form = NovedadForm()
    if request.method == "POST":
        form = NovedadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("nominas:novedad_list")
    return render(request, "nominas/novedad_form.html", {"form": form})

@login_required
def liquidacion_form(request):
    if request.method == "POST":
        form = LiquidacionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("nominas:liquidacion_list")
    else:
        form = LiquidacionForm()

    return render(request, "nominas/liquidacion_form.html", {"form": form})

@login_required
def empleado_update(request, pk: int):
    query = Empleado.objects.get(nro_legajo=pk)
    if request.method == "GET":
        form = EmpleadoForm(instance=query)
    if request.method == "POST":
        form = EmpleadoForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect("nominas:empleado_list")
    return render(request, "nominas/empleado_form.html", {"form": form})

@login_required
def liquidacion_update(request, pk: int):
    query = Liquidacion.objects.get(id=pk)
    if request.method == "GET":
        form = LiquidacionForm(instance=query)
    if request.method == "POST":
        form = LiquidacionForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect("nominas:liquidacion_list")
    return render(request, "nominas/liquidacion_form.html", {"form": form})

@login_required
def empleado_delete(request, pk: int):
    query = Empleado.objects.get(nro_legajo=pk)
    if request.method == "POST":
        query.delete()
        return redirect("nominas:empleado_list")
    return render(request, 'nominas/empleado_confirm_delete.html', {'object':query})

@login_required
def liquidacion_delete(request, pk: int):
    query = Liquidacion.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect("nominas:liquidacion_list")
    return render(request, 'nominas/liquidacion_confirm_delete.html', {'object':query})

@login_required
def novedad_update(request, pk: int):
    query = Novedad.objects.get(id=pk)
    if request.method == "GET":
        form = NovedadForm(instance=query)
    if request.method == "POST":
        form = NovedadForm(request.POST, instance=query)
        if form.is_valid():
            form.save()
            return redirect("nominas:novedad_list")
    return render(request, "nominas/novedad_form.html", {"form": form})

@login_required
def novedad_delete(request, pk: int):
    query = Novedad.objects.get(id=pk)
    if request.method == "POST":
        query.delete()
        return redirect("nominas:novedad_list")
    return render(request, 'nominas/novedad_confirm_delete.html', {'object':query})

@login_required
def novedad_detail(request, pk: int):
    query = Novedad.objects.get(id=pk)
    context = {'object': query}
    return render(request, 'nominas/novedad_detail.html', context)

project/nominas/templates/nominas/base.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nominas</title>
</head>
<body>
    <header>
        <h1 style="color: blue; text-align: center;">
        {% block header %}
        {% endblock header %}
        </h1>
    </header>
    <nav style="text-align: center;">
        {% include 'nominas/navbar.html' %}
    </nav>
    <main style="text-align: center;">
        {% block main %}
        {% endblock main %}
    </main>
</body>
</html>

project/nominas/templates/nominas/empleado_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
Empleados: Eliminar Legajo
{% endblock header %}

{% block main %}
    <p>Esta seguro que desea eliminar el legajo "{{ object.nro_legajo }}, {{ object.nombre_empleado }}, {{ object.apellido_empleado }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button> 
    </form>
    <button>
        <a href="{% url 'nominas:empleado_list' %}">Volver</a>
    </button>
{% endblock main %}

project/nominas/templates/nominas/empleado_detail.html
{% extends 'core/base.html' %}

{% block header %}
Empleados: Vista de Legajo
{% endblock header %}

{% block main %}
    <ul>
        <li>Número de Legajo: {{ object.nro_legajo }}</li>
        <li>Nombre: {{ object.nombre_empleado }}</li>
        <li>Apellido: {{ object.apellido_empleado }}</li>
        <li>DNI: {{ object.dni }}</li>
        <li>Sexo: {{ object.get_sexo_empleado_display }}</li> <!---->
        <li>Celular: {{ object.celular }}</li>
        <li>Email: {{ object.mail }}</li>
        <li>Fecha de Nacimiento: {{ object.fecha_de_nacimiento }}</li>
        <li>Fecha de Ingreso: {{ object.fecha_de_ingreso }}</li>
        <li>Fecha de Egreso: {{ object.fecha_de_egreso }}</li>
        <li>Estado: {{ object.get_estado_display }}</li>
        <li>Nacionalidad: {{ object.nacionalidad }}</li>
        <li>Modalidad de Contratación: {{ object.get_mod_contratacion_display }}</li>
        <li>Puesto: {{ object.puesto }}</li>
        <li>Sueldo: {{ object.sueldo|floatformat:2 }}</li>
        <li>
            Avatar:
            {% if object.avatar %}
                <img src="{{ object.avatar.url }}" alt="Avatar de {{ object.nombre_empleado }}" style="width: 100px; height: auto;">
            {% else %}
                <p>No hay imagen disponible.</p>
            {% endif %}
        </li>
    </ul>
    <button>
        <a href="{% url 'nominas:empleado_list' %}">Volver</a>
    </button>
{% endblock main %}

project/nominas/templates/nominas/empleado_form.html
{% extends 'core/base.html' %}

{% block header %}
    {% if form.instance.pk %}
        Actualizando Legajo
    {% else %}
        Nuevo Legajo
    {% endif %}
{% endblock header %}

{% block main %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock main %}

project/nominas/templates/nominas/empleado_list.html
{% extends 'core/base.html' %}

{% block header %}
Empleados: Registros
{% endblock header %}

{% block main %}
    <form action="{% url 'nominas:empleado_list' %}" method="get">
        <input type="text" name="q" placeholder="Buscar...">
        <button type="submit">Buscar</button>
        <button>
            <a href="{% url 'nominas:empleado_form' %}">Nuevo Legajo</a>
        </button>
    </form>
    <ul>
       {% for object in object_list %}
            <li>{{ object.nro_legajo }}, {{ object.nombre_empleado }}, {{ object.apellido_empleado }}
                <a href="{% url 'nominas:empleado_detail' object.nro_legajo %}">Ver Legajo</a>
                <a href="{% url 'nominas:empleado_update' object.nro_legajo %}">Modificar</a>
                <a href="{% url 'nominas:empleado_delete' object.nro_legajo %}">Eliminar</a>               
            </li>
    {% empty %}
        <p>No hay registros.</p>
    {% endfor %}
    </ul>
{% endblock main %}

project/nominas/templates/nominas/index.html
{% extends 'nominas/base.html' %}

{% block header %}
    Nominas
{% endblock header %}

{% block main %}

{% endblock main %}

project/nominas/templates/nominas/liquidacion_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
Empleados: Eliminar Liquidacion
{% endblock header %}

{% block main %}
    <p>Esta seguro que desea eliminar esta liquidacion "{{ object.empleado.nro_legajo }}, {{ object.empleado.nombre_empleado }}, {{ object.empleado.apellido_empleado }}, {{ object.periodo }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button> 
    </form>
    <button>
        <a href="{% url 'nominas:empleado_list' %}">Volver</a>
    </button>
{% endblock main %}

project/nominas/templates/nominas/liquidacion_create.html
{% extends 'core/base.html' %}

{% block header %}
Liquidaciones: Formulario
{% endblock header %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock main %}

project/nominas/templates/nominas/liquidacion_form.html
{% extends 'core/base.html' %}

{% block header %}
Liquidaciones: Formulario
{% endblock header %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Liquidar</button>
</form>
{% endblock main %}

project/nominas/templates/nominas/novedad_confirm_delete.html
{% extends 'core/base.html' %}

{% block header %}
Empleados: Eliminar Novedad
{% endblock header %}

{% block main %}
    <p>Esta seguro que desea eliminar esta Novedades "{{ object.empleado.nro_legajo }}, {{ object.empleado.nombre_empleado }}, {{ object.empleado.apellido_empleado }}, {{ object.tipo_novedad }}, {{ object.fecha }}"?</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Confirmo</button> 
    </form>
    <button>
        <a href="{% url 'nominas:novedad_list' %}">Volver</a>
    </button>
{% endblock main %}

project/nominas/templates/nominas/novedad_create.html
{% extends 'core/base.html' %}

{% block header %}
Novedades: Formulario
{% endblock header %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock main %}

project/nominas/templates/nominas/novedad_detail.html
{% extends 'core/base.html' %}

{% block header %}
Novedad de Empleado: Detalle
{% endblock header %}

{% block main %}
    <ul>
        <li>Número de Legajo: {{ object.empleado.nro_legajo }}</li>
        <li>Nombre: {{ object.empleado.nombre_empleado }}</li>
        <li>Apellido: {{ object.empleado.apellido_empleado }}</li>
        <li>Tipo de novedad: {{ object.get_tipo_novedad_display }}</li>
        <li>Descripcion: {{ object.descripcion }}</li>
        <li>Fecha: {{ object.fecha }}</li>
        <li>Comentarios: {{ object.comentarios }}</li>
    </ul>
    <button>
        <a href="{% url 'nominas:novedad_list' %}">Volver</a>
    </button>
{% endblock main %}

project/nominas/templates/nominas/novedad_form.html
{% extends 'core/base.html' %}

{% block header %}
Novedades: Formulario
{% endblock header %}

{% block main %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Guardar</button>
</form>
{% endblock main %}

project/nominas/templates/nominas/novedad_list.html
{% extends 'core/base.html' %}

{% block header %}
Novedad: Registro
{% endblock header %}

{% block main %}
    <form action="{% url 'nominas:novedad_list' %}" method="get">
        <input type="text" name="q" placeholder="Buscar...">
        <button type="submit">Buscar</button>
    </form>
        <a href="{% url 'nominas:novedad_form' %}" style="text-decoration:none;">
            <button type="button">Nueva novedad</button>
        </a>
    <ul>
        {% for object in object_list %}
            <li>{{ object.empleado.nro_legajo }}, {{ object.empleado.nombre_empleado }}, {{ object.empleado.apellido_empleado }}, {{ object.fecha }}
                <a href="{% url 'nominas:novedad_detail' object.id %}">Ver novedad</a>
                <a href="{% url 'nominas:novedad_update' object.id %}">Modificar</a>
                <a href="{% url 'nominas:novedad_delete' object.id %}">Eliminar</a>               
            </li>
        {% empty %}
            <p>No hay registros.</p>
        {% endfor %}
    </ul>    
{% endblock main %}